== REST Services Sample Readme
'''

This guide walks you through building and running the REST services sample.  A Java sample is provided using a default ClientBuilder to make calls to a container or server running the REST Services.

=== Sample Program to build and run
SRestClient.java : A java sample client using javax.ws.rs.client.ClientBuilder

Default values may be programmatically changed in the source file or by setting the environment.

Settings used to build the URI where REST services are running::
* PORT
* HOSTNAME

Settings used to authenticate to Content Manager Repository using the login API::
* SERVERNAME
* USERNAME
* PASSWORD

Setting used to locate the directory containing content file resources::
* TESTDOCS_URI

Enable other tests by changing::
* testItemtypes : run endpoint for item type APIs
* testQuery: run endpoint for item query API
* testCRUD: run endpoints to create, retrieve, update and delete item APIs

NOTE: By default only ping test is run.

=== Dependencies
To compile the sample client, you must have the following JAR files:

* CM Rest classes to programmatically build JSON objects to use with the CM Rest endpoints
----
cmrmodel.jar
----
* Java EE that includes JAX-RS
----
api group: 'javax', name: 'javaee-api', version: '8.0.1'
----

* Jersey Client 2.x libraries to handle requests and responses
----
api group: 'org.glassfish.jersey.core', name: 'jersey-client', version: '2.29.1'
api group: 'org.glassfish.jersey.inject', name: 'jersey-hk2', version: '2.29.1'
api group: 'org.glassfish.jersey.media', name: 'jersey-media-json-jackson', version: '2.29.1'
api group: 'org.glassfish.jersey.media', name: 'jersey-media-multipart', version: '2.29.1'
api group: 'org.glassfish.jersey.media', name: 'jersey-media-json-binding', version: '2.29.1'
api group: 'org.glassfish', name: 'javax.el', version: '3.0.1-b11'
----

=== Build
* javac: create class file

=== Run
* java SRestClient

=== Sample Console Output
....
***** GET /ping:  *****
{
  	"cmconnectionpool.properties.resource" : "file:/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/cmgmt/cmbconnectionpool.properties",
  	"status" : "started",
  	"cmrest.properties.resource" : "file:/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/cmgmt/cmrestservices.properties",
  	"CMCFGDIR" : "/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/cmgmt/connectors",
  	"java.runtime.version" : "8.0.6.16 - pxa6480sr6fp16-20200902_01(SR6 FP16)",
  	"os.name" : "Linux",
  	"version" : "8.7.00.000.381 - 2020-12-23 06:25:17:017 PST",
  	"tokenDuration" : "480",
  	"enableConnectionPool" : "false",
  	"CMWorkingDirectory" : "/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides",
  	"cmbcmenv.properties.resource" : "file:/opt/ibm/wlp/usr/servers/defaultServer/apps/expanded/cm8app.war/WEB-INF/classes/cmbcmenv.properties"
}
....
